### ISSUE TITLE
Missing Dotenv

### ISSUE THREAD

**Issue by ognjen-petrovic** [danrovito/Fett#6]
Hi,

There is no Dotenv in required libs.

Also, leading slash is missing here
`$dotenv = new Dotenv\Dotenv('../');`
should be
`$dotenv = new \Dotenv\Dotenv('../');`

Regards, Ognjen

**Comment by danrovito** [comment]
I'm not really sure what you mean here?  It's required via composer and I've tested it works.  Please explain :)

**Comment by ognjen-petrovic** [comment]
I see that it is composer.json, not sure why but it was missing to me after composer install and I had to add it explicitly.
Regarding leading slash...you added "use Dotenv\Dotenv;" so it is not an issue anymore :-)
